# Generated by Django 3.1.4 on 2021-02-05 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('virtual_account_number', models.CharField(max_length=255)),
                ('virtual_account_ifsc_code', models.CharField(max_length=255)),
                ('vpa', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('primary_contact', models.CharField(max_length=255)),
                ('contact_type', models.CharField(max_length=255)),
                ('email_id', models.CharField(max_length=255)),
                ('landline_number', models.IntegerField(null=True)),
                ('mobile_number', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
